pod 'MJRefresh', '~> 3.0.7'
pod 'MMProgressHUD', '~> 0.3.2'
pod 'SDWebImage', '~> 3.7.3'
pod 'CHTCollectionViewWaterfallLayout', '~> 0.9.2'
pod 'YYModel', '~> 0.9.8'
pod 'AFNetworking', '~> 3.0.4'
pod 'Masonry', '~> 0.6.3'
pod 'ViewDeck', '~> 2.4.1'
